From alpine:latest

Run apk add --no-cache python3-dev \
    && pip3 install --upgrade pip

WORKDIR /app

COPY . /app

RUN pip3 --no-cache-dir install -r requirments.txt

EXPOSE 5000

ENTRYPOINT ["python3"]

CMD["app.py"]
